version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./include/metabase-data:/metabase-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_HOST=postgres
      - MB_DB_USER_FILE=/run/secrets/db_user
      - MB_DB_PASS_FILE=/run/secrets/db_password
    secrets:
      - db_user
      - db_password
    ports:
      - 3000:3000
    restart: always

secrets:
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt