version: "3.9"
services:
  metabase:
    image: metabase/metabase:v0.40.5
    volumes:
      - ./include/metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    restart: always

    # healthcheck:
    #   test: curl --fail -I http://localhost:3000/api/health || exit 1
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5

